springdoc.api-docs.groups.enabled=true
springdoc.swagger-ui.tagsSorter=alpha

springdoc.group-configs[0].group=1. Public API
springdoc.group-configs[0].paths-to-match=/,/public/v*/**
springdoc.group-configs[0].packages-to-scan=com.truongbn

springdoc.group-configs[1].group=2. Private API
springdoc.group-configs[1].paths-to-match=/api/v*/**
springdoc.group-configs[1].packages-to-scan=com.truongbn
